version: "3.9"
services:
  api:
    build: .
    container_name: nest-product-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    # depends_on:
    #   - db

  # db:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: demo
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:
