version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    ports:
      - '${APP_PORT:-3000}:${APP_PORT:-3000}'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://${DATABASE_USERNAME:-postgres}:${DATABASE_PASSWORD:-password}@postgres:5432/${DATABASE_NAME:-nest_product_api}
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  postgres:
    image: postgres:15-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-password}
      - POSTGRES_DB=${DATABASE_NAME:-nest_product_api}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
