import { Injectable, Logger, OnApplicationBootstrap } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { SeedLog } from './seed-log.entity';
import { Product } from '../product/product.entity';

@Injectable()
export class SeedService implements OnApplicationBootstrap {
  private readonly logger = new Logger(SeedService.name);

  constructor(
    @InjectRepository(SeedLog) private readonly seedLogRepo: Repository<SeedLog>,
    @InjectRepository(Product) private readonly productRepo: Repository<Product>,
  ) {}

  async onApplicationBootstrap() {
    // Toggle with env var so it doesn’t run in every environment.
    if ((process.env.SEED_ON_START || '').toLowerCase() !== 'true') {
      return;
    }

    const marker = 'products-initialized';
    const already = await this.seedLogRepo.findOne({ where: { name: marker } });
    if (already) {
      this.logger.log('Seed skipped (already initialized).');
      return;
    }

    // Idempotent guard: also skip if data already exists.
    const count = await this.productRepo.count();
    if (count > 0) {
      this.logger.log('Seed skipped (products table not empty).');
      await this.seedLogRepo.save(this.seedLogRepo.create({ name: marker }));
      return;
    }

    // Initial data - comprehensive product catalog
    const items: Partial<Product>[] = [
      {
        code: 'P-STEEL-001',
        name: 'Steel Bolt M8',
        description: 'High tensile steel bolt M8x30',
        categoryId: 10,
        productType: 'finished',
        specifications: 'DIN 933; grade 8.8',
        standardTime: 5,
        unit: 'pcs',
        isActive: true,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        code: 'P-ALU-PLATE',
        name: 'Aluminium Plate 2mm',
        description: 'AL6061 sheet 1x2m',
        categoryId: 12,
        productType: 'finished',
        specifications: '2mm x 1000mm x 2000mm',
        standardTime: 12,
        unit: 'sheet',
        isActive: true,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        code: 'P-PAINT-BLK',
        name: 'Black Paint 1L',
        description: 'Matte black industrial paint',
        categoryId: 15,
        productType: 'finished',
        specifications: '1L can',
        standardTime: 3,
        unit: 'can',
        isActive: true,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        code: 'P-COPPER-WIRE',
        name: 'Copper Wire 2.5mm',
        description: 'Single core copper electrical wire',
        categoryId: 20,
        productType: 'finished',
        specifications: '2.5mm² x 100m reel',
        standardTime: 2,
        unit: 'meter',
        isActive: true,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        code: 'P-RUBBER-SEAL',
        name: 'O-Ring Seal 20mm',
        description: 'NBR rubber O-ring seal',
        categoryId: 18,
        productType: 'finished',
        specifications: '20mm ID x 2mm thickness',
        standardTime: 1,
        unit: 'pcs',
        isActive: true,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        code: 'P-DRILL-BIT-8',
        name: 'HSS Drill Bit 8mm',
        description: 'High speed steel twist drill bit',
        categoryId: 25,
        productType: 'finished',
        specifications: '8mm diameter, 117mm length',
        standardTime: 4,
        unit: 'pcs',
        isActive: true,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        code: 'P-BEARING-6205',
        name: 'Ball Bearing 6205',
        description: 'Deep groove ball bearing',
        categoryId: 22,
        productType: 'finished',
        specifications: '25mm ID x 52mm OD x 15mm width',
        standardTime: 8,
        unit: 'pcs',
        isActive: true,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        code: 'P-STAINLESS-ROD',
        name: 'Stainless Steel Rod 10mm',
        description: '316L stainless steel round bar',
        categoryId: 11,
        productType: 'raw_material',
        specifications: '10mm diameter x 3m length',
        standardTime: 15,
        unit: 'meter',
        isActive: true,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        code: 'P-PLASTIC-TUBE',
        name: 'PVC Pipe 50mm',
        description: 'Pressure rated PVC pipe',
        categoryId: 30,
        productType: 'finished',
        specifications: '50mm diameter x 6m length, PN10',
        standardTime: 6,
        unit: 'meter',
        isActive: true,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        code: 'P-MOTOR-3PH',
        name: '3-Phase Motor 2.2kW',
        description: 'Induction motor with mounting flange',
        categoryId: 35,
        productType: 'finished',
        specifications: '2.2kW, 1450 RPM, B3 mounting',
        standardTime: 45,
        unit: 'pcs',
        isActive: true,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        code: 'P-WASHER-M8',
        name: 'Flat Washer M8',
        description: 'Zinc plated flat washer',
        categoryId: 10,
        productType: 'finished',
        specifications: 'M8 x 16mm OD x 1.6mm thick',
        standardTime: 1,
        unit: 'pcs',
        isActive: true,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        code: 'P-HYDRAULIC-OIL',
        name: 'Hydraulic Oil ISO 46',
        description: 'Premium hydraulic fluid',
        categoryId: 40,
        productType: 'finished',
        specifications: '20L container, ISO VG 46',
        standardTime: 2,
        unit: 'liter',
        isActive: true,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        code: 'P-GEAR-PUMP',
        name: 'Gear Pump GP-25',
        description: 'External gear hydraulic pump',
        categoryId: 45,
        productType: 'finished',
        specifications: '25cc/rev, max 250 bar',
        standardTime: 60,
        unit: 'pcs',
        isActive: true,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        code: 'P-CHAIN-ROLLER',
        name: 'Roller Chain 12B-1',
        description: 'Single strand roller chain',
        categoryId: 50,
        productType: 'finished',
        specifications: '3/4" pitch x 10ft length',
        standardTime: 8,
        unit: 'foot',
        isActive: true,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        code: 'P-VALVE-BALL',
        name: 'Ball Valve 1/2"',
        description: 'Brass ball valve with lever handle',
        categoryId: 55,
        productType: 'finished',
        specifications: '1/2" NPT, full port, 600 WOG',
        standardTime: 12,
        unit: 'pcs',
        isActive: true,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        code: 'P-FILTER-AIR',
        name: 'Air Filter Element',
        description: 'Pleated air filter cartridge',
        categoryId: 60,
        productType: 'finished',
        specifications: '300mm x 200mm x 50mm',
        standardTime: 5,
        unit: 'pcs',
        isActive: true,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        code: 'P-COUPLING-FLEX',
        name: 'Flexible Coupling 25mm',
        description: 'Jaw coupling with spider insert',
        categoryId: 65,
        productType: 'finished',
        specifications: '25mm bore, aluminum hubs',
        standardTime: 20,
        unit: 'pcs',
        isActive: true,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        code: 'P-GASKET-FLANGE',
        name: 'Flange Gasket 100mm',
        description: 'Rubber flange gasket',
        categoryId: 18,
        productType: 'finished',
        specifications: '100mm PN16 full face',
        standardTime: 3,
        unit: 'pcs',
        isActive: true,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        code: 'P-SPRING-COMP',
        name: 'Compression Spring 20x50',
        description: 'Heavy duty compression spring',
        categoryId: 70,
        productType: 'finished',
        specifications: '20mm OD x 50mm length, 5mm wire',
        standardTime: 7,
        unit: 'pcs',
        isActive: true,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        code: 'P-RELAY-24V',
        name: 'Control Relay 24VDC',
        description: 'Industrial control relay',
        categoryId: 75,
        productType: 'finished',
        specifications: '24VDC coil, 4PDT contacts',
        standardTime: 10,
        unit: 'pcs',
        isActive: true,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        code: 'P-HOSE-HYDRAULIC',
        name: 'Hydraulic Hose 3/8"',
        description: 'High pressure hydraulic hose',
        categoryId: 80,
        productType: 'finished',
        specifications: '3/8" ID, 4000 PSI, per meter',
        standardTime: 4,
        unit: 'meter',
        isActive: true,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        code: 'P-SENSOR-TEMP',
        name: 'Temperature Sensor PT100',
        description: 'RTD temperature sensor',
        categoryId: 85,
        productType: 'finished',
        specifications: 'PT100, 3-wire, -50 to +200°C',
        standardTime: 25,
        unit: 'pcs',
        isActive: true,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        code: 'P-BELT-V',
        name: 'V-Belt A42',
        description: 'Classical V-belt',
        categoryId: 90,
        productType: 'finished',
        specifications: 'A section, 42" pitch length',
        standardTime: 6,
        unit: 'pcs',
        isActive: true,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        code: 'P-FUSE-32A',
        name: 'Fuse Cartridge 32A',
        description: 'HRC fuse cartridge',
        categoryId: 95,
        productType: 'finished',
        specifications: '32A, 415V, gG type',
        standardTime: 2,
        unit: 'pcs',
        isActive: true,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        code: 'P-PULLEY-100',
        name: 'Cast Iron Pulley 100mm',
        description: 'Single groove V-belt pulley',
        categoryId: 100,
        productType: 'finished',
        specifications: '100mm PD, 25mm bore, A section',
        standardTime: 18,
        unit: 'pcs',
        isActive: true,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        code: 'P-LUBRICANT-GEAR',
        name: 'Gear Oil SAE 90',
        description: 'Heavy duty gear lubricant',
        categoryId: 105,
        productType: 'finished',
        specifications: 'SAE 90, API GL-4, 5L container',
        standardTime: 3,
        unit: 'liter',
        isActive: true,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        code: 'P-SWITCH-LIMIT',
        name: 'Limit Switch SPDT',
        description: 'Heavy duty limit switch',
        categoryId: 110,
        productType: 'finished',
        specifications: 'SPDT, roller lever, IP65',
        standardTime: 15,
        unit: 'pcs',
        isActive: true,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        code: 'P-CYLINDER-AIR',
        name: 'Pneumatic Cylinder 50x100',
        description: 'Double acting air cylinder',
        categoryId: 115,
        productType: 'finished',
        specifications: '50mm bore x 100mm stroke',
        standardTime: 35,
        unit: 'pcs',
        isActive: true,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        code: 'P-FITTING-ELBOW',
        name: 'Pipe Elbow 90° 1/2"',
        description: 'Threaded pipe elbow',
        categoryId: 120,
        productType: 'finished',
        specifications: '1/2" NPT, 90°, brass',
        standardTime: 4,
        unit: 'pcs',
        isActive: true,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        code: 'P-CONTACTOR-25A',
        name: 'Motor Contactor 25A',
        description: '3-pole motor contactor',
        categoryId: 125,
        productType: 'finished',
        specifications: '25A, 415V, 24VDC coil',
        standardTime: 22,
        unit: 'pcs',
        isActive: true,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        code: 'P-SHAFT-KEY',
        name: 'Parallel Key 8x7x30',
        description: 'Carbon steel parallel key',
        categoryId: 130,
        productType: 'finished',
        specifications: '8mm x 7mm x 30mm, DIN 6885',
        standardTime: 3,
        unit: 'pcs',
        isActive: true,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        code: 'P-INSULATION-FOAM',
        name: 'Foam Insulation 25mm',
        description: 'Closed cell foam insulation',
        categoryId: 135,
        productType: 'finished',
        specifications: '25mm thick x 1m x 2m sheet',
        standardTime: 8,
        unit: 'sheet',
        isActive: true,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        code: 'P-PRESSURE-GAUGE',
        name: 'Pressure Gauge 0-10 bar',
        description: 'Glycerin filled pressure gauge',
        categoryId: 140,
        productType: 'finished',
        specifications: '100mm dial, 1/4" BSP bottom',
        standardTime: 12,
        unit: 'pcs',
        isActive: true,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      {
        code: 'P-CABLE-ARMORED',
        name: 'Armored Cable 4x2.5mm',
        description: 'SWA armored electrical cable',
        categoryId: 145,
        productType: 'finished',
        specifications: '4 core x 2.5mm², per meter',
        standardTime: 6,
        unit: 'meter',
        isActive: true,
        createdBy: 'admin',
        updatedBy: 'admin',
      },
    ];

    await this.productRepo.save(this.productRepo.create(items));
    await this.seedLogRepo.save(this.seedLogRepo.create({ name: marker }));
    this.logger.log('✅ Seeded initial products.');
  }
}
