name: deploy-render
on:
  push:
    branches: [ "main" ]

jobs:
  trigger-render-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Call Render Deploy Hook (service builds from repo)
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          if [ -z "$RENDER_API_KEY" ] || [ -z "$RENDER_SERVICE_ID" ]; then
            echo "Please set RENDER_API_KEY and RENDER_SERVICE_ID secrets"
            exit 1
          fi
          curl -sS -X POST             -H "Authorization: Bearer $RENDER_API_KEY"             -H "Content-Type: application/json"             https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys             -d '{"clearCache": false}'
